// SPDX-License-Identifier: TBD
//
// Password Modify Extended Operation Handler (RFC 3062)
//
// OID: 1.3.6.1.4.1.4203.1.11.1
//
// This operation allows an authorized JIT Broker to set ephemeral passwords
// for user accounts. It is NOT a self-service password change — only
// identities with the broker role may invoke it.
//
// NIST SP 800-53 Rev. 5:
// - IA-5(1) (Password-Based Authentication): Passwords set through this
//   operation are ephemeral, generated by the JIT Broker, and stored as
//   hashes in the site-local runtime schema. They are never replicated.
// - AC-3 (Access Control Enforcement): Only authenticated sessions with a
//   recognized broker DN may invoke this operation. All other callers receive
//   `insufficientAccessRights`. This enforces the broker authorization boundary
//   — the LDAP server is a password store, not a password policy engine.

use std::future::Future;
use std::pin::Pin;

use super::codec::{
    CodecError, ExtendedRequest, ExtendedResponse, LdapResult, ResultCode,
};
use super::session::LdapSession;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// OID for the Password Modify Extended Operation (RFC 3062).
pub const PASSWORD_MODIFY_OID: &str = "1.3.6.1.4.1.4203.1.11.1";

// ---------------------------------------------------------------------------
// PasswdModifyRequestValue parsing
// ---------------------------------------------------------------------------

/// Parsed fields from a PasswdModifyRequestValue (RFC 3062 Section 2).
///
/// ```text
/// PasswdModifyRequestValue ::= SEQUENCE {
///     userIdentity [0] OCTET STRING OPTIONAL,
///     oldPasswd    [1] OCTET STRING OPTIONAL,
///     newPasswd    [2] OCTET STRING OPTIONAL
/// }
/// ```
#[derive(Debug, Clone)]
pub struct PasswdModifyRequest {
    /// The DN of the user whose password is being set.
    /// If absent, applies to the bound identity (not used in our broker model).
    pub user_identity: Option<String>,
    /// Old password — ignored by this server. The JIT Broker does not need
    /// to know the previous password.
    pub old_passwd: Option<Vec<u8>>,
    /// New password to set.
    pub new_passwd: Option<Vec<u8>>,
}

/// Parse a PasswdModifyRequestValue from the ExtendedRequest's requestValue bytes.
pub fn parse_passwd_modify_request(value: &[u8]) -> Result<PasswdModifyRequest, CodecError> {
    use super::codec::{decode_length, decode_tag, decode_tlv};

    // The value should be a SEQUENCE.
    let (tag, seq_contents, _) = decode_tlv(value)?;
    if tag != 0x30 {
        return Err(CodecError::InvalidFormat(format!(
            "PasswdModifyRequestValue must be SEQUENCE, got 0x{tag:02x}"
        )));
    }

    let mut user_identity = None;
    let mut old_passwd = None;
    let mut new_passwd = None;

    let mut offset = 0;
    while offset < seq_contents.len() {
        let (field_tag, field_tag_len) = decode_tag(&seq_contents[offset..])?;
        let (field_len, field_len_len) = decode_length(&seq_contents[offset + field_tag_len..])?;
        let header_len = field_tag_len + field_len_len;
        // Bounds check: prevent panic on malformed length field.
        if offset + header_len + field_len > seq_contents.len() {
            return Err(CodecError::InvalidFormat(
                "PasswdModifyRequestValue field length exceeds available data".into(),
            ));
        }
        let field_value = &seq_contents[offset + header_len..offset + header_len + field_len];

        match field_tag {
            0x80 => {
                // [0] userIdentity
                user_identity = Some(
                    String::from_utf8(field_value.to_vec())
                        .map_err(|_| CodecError::InvalidUtf8)?,
                );
            }
            0x81 => {
                // [1] oldPasswd — we accept but ignore it.
                old_passwd = Some(field_value.to_vec());
            }
            0x82 => {
                // [2] newPasswd
                new_passwd = Some(field_value.to_vec());
            }
            _ => {
                // Unknown field — skip per forward-compatibility.
                tracing::debug!("ignoring unknown PasswdModifyRequestValue field tag 0x{field_tag:02x}");
            }
        }

        offset += header_len + field_len;
    }

    Ok(PasswdModifyRequest {
        user_identity,
        old_passwd,
        new_passwd,
    })
}

// ---------------------------------------------------------------------------
// Password store trait
// ---------------------------------------------------------------------------

/// Outcome of a password modification attempt.
#[derive(Debug, Clone)]
pub enum PasswordModifyResult {
    /// Password was successfully set.
    Success,
    /// The target user does not exist.
    UserNotFound,
    /// An internal error occurred.
    InternalError(String),
}

/// Trait for pluggable password storage.
///
/// The Runtime agent will provide a concrete implementation backed by the
/// site-local PostgreSQL runtime schema.
pub trait PasswordStore: Send + Sync {
    /// Set a new password for the specified user.
    ///
    /// # Arguments
    /// - `user_dn`: The distinguished name of the user.
    /// - `new_password`: The new password bytes (will be hashed by the implementation).
    /// - `broker_dn`: The DN of the broker performing the operation (for audit).
    ///
    /// # NIST IA-5(1): Password-Based Authentication
    /// Implementations MUST hash the password before storage and zeroize the
    /// plaintext bytes after hashing.
    fn set_password<'a>(
        &'a self,
        user_dn: &'a str,
        new_password: &'a [u8],
        broker_dn: &'a str,
    ) -> Pin<Box<dyn Future<Output = PasswordModifyResult> + Send + 'a>>;
}

// ---------------------------------------------------------------------------
// Broker authorization
// ---------------------------------------------------------------------------

/// Trait for checking whether a bound identity is an authorized broker.
///
/// # NIST AC-3: Access Control Enforcement
/// Only recognized broker identities may invoke the Password Modify operation.
/// This trait abstracts the authorization check so it can be backed by
/// configuration, database lookup, or certificate attributes.
pub trait BrokerAuthorizer: Send + Sync {
    /// Returns `true` if the given DN is authorized to perform password
    /// modifications on behalf of users.
    fn is_authorized_broker(&self, dn: &str) -> bool;
}

// ---------------------------------------------------------------------------
// Audit info returned alongside the response
// ---------------------------------------------------------------------------

/// Information about a password modify operation for audit logging.
///
/// Returned alongside the `ExtendedResponse` so the caller (LdapHandler)
/// can emit a structured audit event without re-parsing the request.
#[derive(Debug, Clone)]
pub struct PasswordModifyAuditInfo {
    /// DN of the broker that performed the operation.
    pub broker_dn: String,
    /// DN of the user whose password was modified (or attempted).
    pub target_dn: String,
    /// Whether the operation succeeded.
    pub success: bool,
    /// Human-readable failure reason, if any.
    pub failure_reason: Option<String>,
}

// ---------------------------------------------------------------------------
// Password Modify handler
// ---------------------------------------------------------------------------

/// Handles the Password Modify Extended Operation (RFC 3062).
pub struct PasswordModifyHandler<S: PasswordStore, A: BrokerAuthorizer> {
    store: S,
    authorizer: A,
}

impl<S: PasswordStore, A: BrokerAuthorizer> PasswordModifyHandler<S, A> {
    /// Create a new handler with the given password store and broker authorizer.
    pub fn new(store: S, authorizer: A) -> Self {
        Self { store, authorizer }
    }

    /// Process a Password Modify ExtendedRequest.
    ///
    /// Validates:
    /// 1. The session is bound.
    /// 2. The bound identity is an authorized broker (AC-3).
    /// 3. The request contains a valid PasswdModifyRequestValue.
    /// 4. A target user and new password are specified.
    ///
    /// # NIST AC-3: Broker Authorization Boundary
    /// This is the enforcement point for the broker authorization check.
    /// Non-broker identities receive `insufficientAccessRights` regardless
    /// of the request contents.
    pub async fn handle_password_modify(
        &self,
        req: &ExtendedRequest,
        session: &LdapSession,
    ) -> (ExtendedResponse, Option<PasswordModifyAuditInfo>) {
        // Verify the OID matches.
        if req.request_name != PASSWORD_MODIFY_OID {
            return (ExtendedResponse {
                result: LdapResult {
                    result_code: ResultCode::ProtocolError,
                    matched_dn: String::new(),
                    diagnostic_message: format!(
                        "expected OID {}, got {}",
                        PASSWORD_MODIFY_OID, req.request_name
                    ),
                },
                response_name: None,
                response_value: None,
            }, None);
        }

        // NIST AC-3: Verify the session is bound.
        let bind_info = match session.bind_info() {
            Some(info) => info,
            None => {
                tracing::warn!(
                    peer = %session.peer_addr(),
                    "password modify rejected: not bound"
                );
                return (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::OperationsError,
                        matched_dn: String::new(),
                        diagnostic_message: "bind required".into(),
                    },
                    response_name: None,
                    response_value: None,
                }, None);
            }
        };

        // NIST AC-3: Verify the bound identity is an authorized broker.
        if !self.authorizer.is_authorized_broker(&bind_info.dn) {
            tracing::warn!(
                peer = %session.peer_addr(),
                dn = %bind_info.dn,
                "password modify rejected: not a broker"
            );
            return (ExtendedResponse {
                result: LdapResult {
                    result_code: ResultCode::InsufficientAccessRights,
                    matched_dn: String::new(),
                    diagnostic_message: "only authorized brokers may modify passwords".into(),
                },
                response_name: None,
                response_value: None,
            }, Some(PasswordModifyAuditInfo {
                broker_dn: bind_info.dn.clone(),
                target_dn: String::new(),
                success: false,
                failure_reason: Some("not an authorized broker".into()),
            }));
        }

        // Parse the request value.
        let request_value = match &req.request_value {
            Some(v) => v,
            None => {
                return (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::ProtocolError,
                        matched_dn: String::new(),
                        diagnostic_message: "missing PasswdModifyRequestValue".into(),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: String::new(),
                    success: false,
                    failure_reason: Some("missing request value".into()),
                }));
            }
        };

        let parsed = match parse_passwd_modify_request(request_value) {
            Ok(p) => p,
            Err(e) => {
                tracing::warn!(
                    peer = %session.peer_addr(),
                    error = %e,
                    "password modify: failed to parse request"
                );
                return (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::ProtocolError,
                        matched_dn: String::new(),
                        diagnostic_message: format!("malformed request: {e}"),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: String::new(),
                    success: false,
                    failure_reason: Some(format!("malformed request: {e}")),
                }));
            }
        };

        // Require a target user identity.
        let target_dn = match &parsed.user_identity {
            Some(dn) if !dn.is_empty() => dn.as_str(),
            _ => {
                return (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::UnwillingToPerform,
                        matched_dn: String::new(),
                        diagnostic_message: "userIdentity is required".into(),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: String::new(),
                    success: false,
                    failure_reason: Some("userIdentity is required".into()),
                }));
            }
        };

        // Require a new password.
        let new_password = match &parsed.new_passwd {
            Some(pw) if !pw.is_empty() => pw.as_slice(),
            _ => {
                return (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::UnwillingToPerform,
                        matched_dn: String::new(),
                        diagnostic_message: "newPasswd is required".into(),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: target_dn.to_string(),
                    success: false,
                    failure_reason: Some("newPasswd is required".into()),
                }));
            }
        };

        // Delegate to the password store.
        // NIST IA-5(1): The store is responsible for hashing and zeroizing.
        let result = self
            .store
            .set_password(target_dn, new_password, &bind_info.dn)
            .await;

        match result {
            PasswordModifyResult::Success => {
                tracing::info!(
                    peer = %session.peer_addr(),
                    broker = %bind_info.dn,
                    target = %target_dn,
                    "password modified successfully"
                );
                (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::Success,
                        matched_dn: String::new(),
                        diagnostic_message: String::new(),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: target_dn.to_string(),
                    success: true,
                    failure_reason: None,
                }))
            }
            PasswordModifyResult::UserNotFound => {
                tracing::warn!(
                    peer = %session.peer_addr(),
                    target = %target_dn,
                    "password modify: user not found"
                );
                (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::NoSuchObject,
                        matched_dn: String::new(),
                        diagnostic_message: "target user not found".into(),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: target_dn.to_string(),
                    success: false,
                    failure_reason: Some("target user not found".into()),
                }))
            }
            PasswordModifyResult::InternalError(detail) => {
                tracing::error!(
                    peer = %session.peer_addr(),
                    error = %detail,
                    "password modify: internal error"
                );
                (ExtendedResponse {
                    result: LdapResult {
                        result_code: ResultCode::Other,
                        matched_dn: String::new(),
                        diagnostic_message: "internal server error".into(),
                    },
                    response_name: None,
                    response_value: None,
                }, Some(PasswordModifyAuditInfo {
                    broker_dn: bind_info.dn.clone(),
                    target_dn: target_dn.to_string(),
                    success: false,
                    failure_reason: Some(format!("internal error: {detail}")),
                }))
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Placeholder implementations for testing / development
// ---------------------------------------------------------------------------

/// A password store that always succeeds.
pub struct PlaceholderPasswordStore;

impl PasswordStore for PlaceholderPasswordStore {
    fn set_password<'a>(
        &'a self,
        _user_dn: &'a str,
        _new_password: &'a [u8],
        _broker_dn: &'a str,
    ) -> Pin<Box<dyn Future<Output = PasswordModifyResult> + Send + 'a>> {
        Box::pin(async { PasswordModifyResult::Success })
    }
}

/// A broker authorizer that accepts a fixed list of DNs.
pub struct StaticBrokerAuthorizer {
    pub authorized_dns: Vec<String>,
}

impl BrokerAuthorizer for StaticBrokerAuthorizer {
    fn is_authorized_broker(&self, dn: &str) -> bool {
        self.authorized_dns.iter().any(|d| d == dn)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ldap::codec;
    use std::net::{IpAddr, Ipv4Addr, SocketAddr};

    fn test_addr() -> SocketAddr {
        SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), 12345)
    }

    fn make_broker_session() -> LdapSession {
        let mut session = LdapSession::new(test_addr());
        session.transition_to_bound("cn=broker,ou=services,dc=example,dc=com".into());
        session
    }

    fn make_user_session() -> LdapSession {
        let mut session = LdapSession::new(test_addr());
        session.transition_to_bound("cn=normaluser,dc=example,dc=com".into());
        session
    }

    fn make_authorizer() -> StaticBrokerAuthorizer {
        StaticBrokerAuthorizer {
            authorized_dns: vec!["cn=broker,ou=services,dc=example,dc=com".into()],
        }
    }

    /// Build a PasswdModifyRequestValue with userIdentity and newPasswd.
    fn build_passwd_modify_value(user_dn: &str, new_passwd: &[u8]) -> Vec<u8> {
        let mut inner = Vec::new();
        // [0] userIdentity
        inner.extend_from_slice(&codec::encode_tlv(0x80, user_dn.as_bytes()));
        // [2] newPasswd
        inner.extend_from_slice(&codec::encode_tlv(0x82, new_passwd));
        // Wrap in SEQUENCE
        codec::encode_sequence(&inner)
    }

    #[tokio::test]
    async fn test_successful_password_modify() {
        let handler = PasswordModifyHandler::new(PlaceholderPasswordStore, make_authorizer());
        let session = make_broker_session();
        let req = ExtendedRequest {
            request_name: PASSWORD_MODIFY_OID.into(),
            request_value: Some(build_passwd_modify_value(
                "cn=jdoe,dc=example,dc=com",
                b"newpassword123",
            )),
        };
        let (resp, audit_info) = handler.handle_password_modify(&req, &session).await;
        assert_eq!(resp.result.result_code, ResultCode::Success);
        let info = audit_info.unwrap();
        assert!(info.success);
        assert_eq!(info.target_dn, "cn=jdoe,dc=example,dc=com");
    }

    #[tokio::test]
    async fn test_non_broker_rejected() {
        let handler = PasswordModifyHandler::new(PlaceholderPasswordStore, make_authorizer());
        let session = make_user_session();
        let req = ExtendedRequest {
            request_name: PASSWORD_MODIFY_OID.into(),
            request_value: Some(build_passwd_modify_value(
                "cn=jdoe,dc=example,dc=com",
                b"newpassword123",
            )),
        };
        let (resp, audit_info) = handler.handle_password_modify(&req, &session).await;
        assert_eq!(resp.result.result_code, ResultCode::InsufficientAccessRights);
        let info = audit_info.unwrap();
        assert!(!info.success);
        assert!(info.failure_reason.is_some());
    }

    #[tokio::test]
    async fn test_unbound_session_rejected() {
        let handler = PasswordModifyHandler::new(PlaceholderPasswordStore, make_authorizer());
        let session = LdapSession::new(test_addr()); // not bound
        let req = ExtendedRequest {
            request_name: PASSWORD_MODIFY_OID.into(),
            request_value: Some(build_passwd_modify_value(
                "cn=jdoe,dc=example,dc=com",
                b"newpassword123",
            )),
        };
        let (resp, audit_info) = handler.handle_password_modify(&req, &session).await;
        assert_eq!(resp.result.result_code, ResultCode::OperationsError);
        // No audit info for unbound sessions (no identity to attribute).
        assert!(audit_info.is_none());
    }

    #[tokio::test]
    async fn test_missing_new_passwd_rejected() {
        let handler = PasswordModifyHandler::new(PlaceholderPasswordStore, make_authorizer());
        let session = make_broker_session();
        // Build request with only userIdentity, no newPasswd.
        let mut inner = Vec::new();
        inner.extend_from_slice(&codec::encode_tlv(0x80, b"cn=jdoe,dc=example,dc=com"));
        let value = codec::encode_sequence(&inner);
        let req = ExtendedRequest {
            request_name: PASSWORD_MODIFY_OID.into(),
            request_value: Some(value),
        };
        let (resp, audit_info) = handler.handle_password_modify(&req, &session).await;
        assert_eq!(resp.result.result_code, ResultCode::UnwillingToPerform);
        let info = audit_info.unwrap();
        assert!(!info.success);
    }

    #[tokio::test]
    async fn test_wrong_oid_rejected() {
        let handler = PasswordModifyHandler::new(PlaceholderPasswordStore, make_authorizer());
        let session = make_broker_session();
        let req = ExtendedRequest {
            request_name: "1.2.3.4.5.6.7".into(),
            request_value: None,
        };
        let (resp, _audit_info) = handler.handle_password_modify(&req, &session).await;
        assert_eq!(resp.result.result_code, ResultCode::ProtocolError);
    }
}
